name: .NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '5.x'  # Adjust to your specific .NET Core version

      - name: Install .NET Framework Build Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process -Wait -NoNewWindow -FilePath .\vs_buildtools.exe -ArgumentList `
            '--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', `
            '--add Microsoft.VisualStudio.Workload.NetWeb', `
            '--add Microsoft.VisualStudio.Workload.WebBuildTools', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebDeploy', `
            '--quiet', '--wait', '--norestart', '--nocache'

      - name: Restore NuGet Packages
        run: nuget restore .\HRSolution.sln

      - name: Build and Publish
        run: |
          dotnet build .\HRSolution.sln -c Release
          dotnet publish .\HRWebsite\HRWebsite.csproj -c Release -o ./publish

      - name: Verify Published Files
        run: |
          if (Test-Path -Path .\publish) {
            Write-Output "Publish directory exists and contains:"
            Get-ChildItem -Path .\publish
          } else {
            Write-Error "Publish directory does not exist."
            exit 1
          }

      - name: Save Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-files
          path: publish
