name: .NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install dependencies
        run: dotnet restore

      - name: Install ASP.NET Workload
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https
          sudo apt-get update && sudo apt-get install -y dotnet-sdk-7.0

      - name: Build projects individually
        run: |
          for proj in $(find . -name '*.csproj'); do
            dotnet build "$proj" --configuration Release --output ./Build
          done

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: ./Build
