name: .NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Install Visual Studio Build Tools
        run: |
          # Download Visual Studio Build Tools installer
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          # Install required workloads
          Start-Process -Wait -NoNewWindow -FilePath .\vs_buildtools.exe -ArgumentList `
            '--add Microsoft.VisualStudio.Component.WebBuildTools', `
            '--add Microsoft.VisualStudio.ComponentGroup.Web', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebDeploy', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebDevelopment', `
            '--quiet', '--wait', '--norestart', '--nocache'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --output ./Build

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: ./Build
