name: .NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework Build Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process -Wait -NoNewWindow -FilePath .\vs_buildtools.exe -ArgumentList `
            '--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', `
            '--add Microsoft.VisualStudio.Workload.NetWeb', `
            '--add Microsoft.VisualStudio.Workload.WebBuildTools', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebDeploy', `
            '--quiet', '--wait', '--norestart', '--nocache'

      - name: Restore NuGet Packages
        run: nuget restore .\HRSolution.sln

      - name: Find and Use MSBuild
        id: find-msbuild
        shell: powershell
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-Not (Test-Path $vswhere)) {
            Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vswhere.exe -OutFile $vswhere
          }
          $msbuildPath = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          if (-Not $msbuildPath) {
            Write-Error "MSBuild executable not found"
            exit 1
          }
          echo "MSBuild found at: $msbuildPath"
          cd HRWebsite
          & $msbuildPath ..\HRSolution.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml
          echo "MSBUILD_PATH=$msbuildPath" >> $env:GITHUB_ENV

      - name: Publish to folder
        shell: powershell
        run: |
          $msbuildPath = $env:MSBUILD_PATH
          $projectPath = Resolve-Path -Path .\HRSolution.sln
          $publishPath = Join-Path -Path $projectPath -ChildPath "publish"
          New-Item -ItemType Directory -Path $publishPath -Force
          & $msbuildPath ..\HRSolution.sln /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=Properties\PublishProfiles\FolderProfile.pubxml /p:PublishDir=$publishPath

      - name: Verify Published Files
        run: |
          if (Test-Path -Path .\publish) {
            Write-Output "Publish directory exists and contains:"
            Get-ChildItem -Path .\publish
          } else {
            Write-Error "Publish directory does not exist."
            exit 1
          }

      - name: Save Published Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-files
          path: publish
