name: .NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework Build Tools
        run: |
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          Start-Process -Wait -NoNewWindow -FilePath .\vs_buildtools.exe -ArgumentList `
            '--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', `
            '--add Microsoft.VisualStudio.Workload.NetWeb', `
            '--add Microsoft.VisualStudio.Workload.WebBuildTools', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebDeploy', `
            '--quiet', '--wait', '--norestart', '--nocache'

      - name: Restore NuGet Packages
        run: nuget restore .\HRSolution.sln

      - name: Find and Use MSBuild
        shell: powershell
        run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          if (-Not (Test-Path $vswhere)) {
            Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vswhere.exe -OutFile $vswhere
          }
          $msbuildPath = & $vswhere -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
          if (-Not $msbuildPath) {
            Write-Error "MSBuild executable not found"
            exit 1
          }
          echo "MSBuild found at: $msbuildPath"
          & $msbuildPath .\HRSolution.sln /p:Configuration=Release

      - name: Locate Build Output
        run: |
          Write-Output "Searching for build output..."
          Get-ChildItem -Path . -Recurse -Filter *.dll -Name | ForEach-Object { Write-Output "Found: $_" }
          Write-Output "Searching for obj and bin folders..."
          Get-ChildItem -Path . -Recurse -Directory -Include obj, bin | ForEach-Object { Write-Output "Found folder: $_" }

