name: .NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Framework Build Tools
        run: |
          # Download Visual Studio Build Tools installer
          Invoke-WebRequest -Uri https://aka.ms/vs/17/release/vs_buildtools.exe -OutFile vs_buildtools.exe
          # Install required workloads for .NET Framework 4.8
          Start-Process -Wait -NoNewWindow -FilePath .\vs_buildtools.exe -ArgumentList `
            '--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools', `
            '--add Microsoft.VisualStudio.Workload.NetWeb', `
            '--add Microsoft.VisualStudio.Workload.WebBuildTools', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions', `
            '--add Microsoft.VisualStudio.ComponentGroup.WebDeploy', `
            '--quiet', '--wait', '--norestart', '--nocache'

      - name: Find MSBuild Path
        shell: powershell
        run: |
          $msbuildPath = Get-Command msbuild | Select-Object -ExpandProperty Definition
          if (-Not $msbuildPath) {
            Write-Error "MSBuild executable not found in PATH"
            exit 1
          }
          echo "MSBuild found at: $msbuildPath"
          & $msbuildPath .\HRSolution.sln /p:Configuration=Release

      - name: Save Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: ./Build
